esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO0
      mode:
        input: True
        pullup: True
      inverted: True
      ignore_strapping_warning: True
    internal: True
