binary_sensor:
  - id: !extend boot_button
    filters:
      - delayed_on: 50ms 
    on_multi_click:
      - timing:
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for at least 5s 
        then:
          - button.press: factory_reset_button

button:
  - platform: factory_reset
    id: factory_reset_button
    internal: True
