# This is the firmware factory for the LG Controller external component on the ESP32-DevKitC developement board.
# It is used to greate plug and play formware for the given board. 

packages:
  # Include all of the core configuration
  core: !include lg-controller-esp32-devkitc.yaml
  factory_reset: !include factory_reset.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: rrooggiieerr.lg-controller-esp32-devkitc
    version: dev # This will be replaced by the github workflows with the `release` version

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# This points to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://rrooggiieerr/esphome-lg-controller/lg-controller-esp32-devkitc.yaml@main

# Set up Bluetooth LE to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: boot_button

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
  next_url: https://github.com/rrooggiieerr/esphome-lg-controller

# Used to pull OTA updates
http_request:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://github.com/rrooggiieerr/esphome-lg-controller/releases/latest/download/lg-controller-esp32-devkitc.manifest.json
